index:
    path: /
    controller: App\Controller\IndexController::index
conditions:
    path: /conditions
    controller: App\Controller\ConditionsController::conditions
cars:
    path: /cars
    controller: App\Controller\CarsController::cars
